server:
  port: 9080


spring:
  application:
    name: hello-gateway
  cloud:
    gateway:
      routes:
        # 路由到httpbin.org的示例
        - id: httpbin_route
          uri: http://httpbin.org
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        # 路由到本地测试控制器的示例
        - id: test_route
          uri: http://localhost:9080
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1



# logging
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.example: DEBUG